# Generated by Django 6.0.6 on 2026-07-04 22:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_customer_user_and_invoice_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='saldo_efectivo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo disponible en efectivo de este cliente.', max_digits=12, verbose_name='Saldo en Efectivo'),
        ),
        migrations.AddField(
            model_name='customer',
            name='saldo_tarjeta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo disponible en tarjeta de este cliente.', max_digits=12, verbose_name='Saldo en Tarjeta'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=10, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema asociado a esta factura (opcional si se elige un Cliente).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_as_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Cliente externo asociado a esta factura (opcional si se elige un Usuario).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.customer', verbose_name='Cliente'),
        ),
    ]
