# Generated by Django 6.0.6 on 2026-07-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_products', 'Puede ver el módulo de Productos'), ('view_purchases', 'Puede ver el módulo de Compras'), ('view_invoices', 'Puede ver el módulo de Facturas'), ('view_customers', 'Puede ver el módulo de Clientes'), ('view_reports', 'Puede ver el módulo de Reportes'), ('view_security', 'Puede ver el módulo de Seguridad')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
