# Generated by Django 6.0.6 on 2026-07-04 22:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_backfill_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cedula',
            field=models.CharField(blank=True, help_text='Número de cédula/identificación del usuario.', max_length=20, null=True, verbose_name='Cédula'),
        ),
        migrations.AddField(
            model_name='profile',
            name='saldo_efectivo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo disponible en efectivo, editable manualmente por el usuario.', max_digits=12, verbose_name='Saldo en Efectivo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='saldo_tarjeta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo disponible en tarjeta, editable manualmente por el usuario.', max_digits=12, verbose_name='Saldo en Tarjeta'),
        ),
    ]
