# Generated by Django 6.0.6 on 2026-07-04 23:46

import security.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_profile_cedula_profile_saldo_efectivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cedula',
            field=models.CharField(blank=True, help_text='Número de cédula ecuatoriana del usuario (10 dígitos, opcional).', max_length=10, null=True, validators=[security.validators.validate_cedula_ecuatoriana], verbose_name='Cédula'),
        ),
    ]
